version: "3"

services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 4000:8080
    environment:
      - DB_HOST=db
      - DB_NAME=fyler
      - DB_USER=root
      - DB_PASS=root

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fyler
